trigger:
  - main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: e2e
    displayName: Executing E2E Tests
    steps:
    - checkout: self
    - checkout: git://Motify/Motify
    - script: cd Motify

    - script: docker-compose up -d rabbitmq db redis
      displayName: Run required services

    - script: docker-compose up -d --build
      displayName: Run all services
    - script: cd ../webclient

    - script: npm install
    - script: npm start
      displayName: Run web client
    - script: sleep 5

    - script: cypress run

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/tests/test*.xml'
