name: Azure Static Web Apps CI/CD

trigger:
  branches:
    include:
      - main

jobs:
  - job: build_and_deploy_job
    displayName: Build and Deploy Job
    pool:
      vmImage: ubuntu-latest
    variables:
      - group: azure-static-web-apps
    steps:
      - checkout: self
        submodules: true
      - task: Bash@3
        displayName: Build
        inputs:
          targetType: 'inline'
          script: |        
            npm install 
            npm run build
        env:
          REACT_APP_API_URL: $(API_URL)
          REACT_APP_CLIENT_ID: $(CLIENT_ID)

      - task: AzureStaticWebApp@0
        displayName: Deploy
        inputs:
          app_location: '/'
          app_build_command: 'echo 1'
          output_location: 'build'
        env:
          azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_PLANT_0FFDCBB10)
