trigger:
  - main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: e2e
    displayName: Executing E2E Tests
    steps:
    - checkout: self
    - checkout: git://Motify/Motify
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'docker-compose up -d rabbitmq redis db'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Motify'
      displayName: Run required services
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'docker-compose up -d --build'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Motify'
      displayName: Run all services
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          npm install
          npx pm2 start npm -- start
          sleep 5
          npx cypress run
        workingDirectory: '$(System.DefaultWorkingDirectory)/webclient'
      displayName: Run Tests
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/tests/test*.xml'
